server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: quora-api

  datasource:
    url: jdbc:postgresql://localhost:5433/quora
    username: postgres
    password: Amita@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect